### PR TITLE
Pr template ideas

### PR DESCRIPTION
**Pull request by phated**
Seems very meta to use the old PR template on this PR for a new template, so let's just use this as a place for discussion.

I've been noticing some variance in how people fill out the current template and I've tried to reduce vagueness in each question.

Please give me feedback.

### CODE REVIEW

**Comment by warbrett** [comment]
:+1: Those seem to be the 4 I always use with some slight variations in the wording to make them more general. I like it.

**Comment by monteslu** [comment]
:+1: as well.  I like the removal of the generic questions section.  Felt a bit redundant to the first item.

**Comment by alysonz** [comment]
:+1:

**Comment by 2fast2fourier** [comment]
:+1: x :100:

**Comment by urbantumbleweed** [comment]
:+1:

**Pull request merged**
